base: https://api.teamleader.eu
auth:
    header_name: Authorization
    header_value_prefix: Bearer
    high_privileged_access_token: abc
    low_privileged_access_token: def
vars:
    userId:
        high_privileged: 123
        low_privileged: 456
api:
    methods: [GET, POST, PUT, PATCH, DELETE, OPTIONS]
    endpoints:
        users.info:
            operation: READ
            method: GET
            content_type: JSON
            request_params:
            body_params:
                id: $userId
